### ISSUE TITLE
icon missing from dock and appmenu

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.kde.ktorrent#1]
Hi, I using Ubuntu 20.04. 64 bit.
I installed ktorrent from terminal.
After installing that app appears from appmenu except the icon.
After running the icon is missing from Ubuntu dock.

**Comment by cho2** [comment]
@Lvaskz Can you send a screenshot?

**Comment by Lvaskz** [comment]
![appenu](https://user-images.githubusercontent.com/29207169/96955525-045f7b80-14b3-11eb-8c36-98c11c0cf340.png)
![ksnip_20201022-055506](https://user-images.githubusercontent.com/29207169/96955548-13462e00-14b3-11eb-9a9b-a8f68a085845.png)

**Comment by cho2** [comment]
@Lvaskz Can you help to test it? https://github.com/flathub/org.kde.ktorrent/pull/2#issuecomment-714903679

**Comment by Lvaskz** [comment]
Well,I can say that icon from appmenu and ubuntu dock is shown properly.
By other hand, it takes long time to start.🤪
But icons shown properly
Thanks😃
